fix: add system tests and cert/key (#394)
* fix: add mtls system tests and testing cert/key

* update

diff --git a/packages/gapic-generator/.circleci/config.yml b/packages/gapic-generator/.circleci/config.yml
--- a/packages/gapic-generator/.circleci/config.yml
+++ b/packages/gapic-generator/.circleci/config.yml
@@ -91,7 +91,29 @@ workflows:
           filters:
             tags:
               only: /^\d+\.\d+\.\d+$/
+      - showcase-mtls:
+          requires:
+            - docs
+            - mypy
+            - showcase-unit-3.6
+            - showcase-unit-3.7
+            - showcase-unit-3.8
+            - showcase-mypy
+          filters:
+            tags:
+              only: /^\d+\.\d+\.\d+$/
       - showcase-alternative-templates:
+          requires:
+            - docs
+            - mypy
+            - showcase-unit-alternative-templates-3.6
+            - showcase-unit-alternative-templates-3.7
+            - showcase-unit-alternative-templates-3.8
+            - showcase-mypy-alternative-templates
+          filters:
+            tags:
+              only: /^\d+\.\d+\.\d+$/
+      - showcase-mtls-alternative-templates:
           requires:
             - docs
             - mypy
@@ -207,7 +229,7 @@ jobs:
   showcase:
     docker:
       - image: python:3.8-slim
-      - image: gcr.io/gapic-images/gapic-showcase:0.6.1
+      - image: gcr.io/gapic-images/gapic-showcase:0.8.1
     steps:
       - checkout
       - run:
@@ -229,10 +251,51 @@ jobs:
       - run:
           name: Run showcase tests.
           command: nox -s showcase
+  showcase-mtls:
+    working_directory: /tmp/workspace
+    docker:
+      - image: python:3.8-slim
+    steps:
+      - checkout
+      - run:
+          name: Install system dependencies.
+          command: |
+            apt-get update
+            apt-get install -y curl pandoc unzip
+      - run:
+          name: Install nox.
+          command: pip install nox
+      - run:
+          name: Install protoc 3.7.1.
+          command: |
+            mkdir -p /usr/src/protoc/
+            curl --location https://github.com/google/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-x86_64.zip --output /usr/src/protoc/protoc-3.7.1.zip
+            cd /usr/src/protoc/
+            unzip protoc-3.7.1.zip
+            ln -s /usr/src/protoc/bin/protoc /usr/local/bin/protoc
+      - run:
+          name: Run showcase tests.
+          command:  |
+            mkdir gapic_showcase
+            cd gapic_showcase
+            curl -sSL https://github.com/googleapis/gapic-showcase/releases/download/v0.8.1/gapic-showcase-0.8.1-linux-amd64.tar.gz | tar xz
+            ./gapic-showcase run --mtls-ca-cert=/tmp/workspace/tests/cert/mtls.crt --mtls-cert=/tmp/workspace/tests/cert/mtls.crt --mtls-key=/tmp/workspace/tests/cert/mtls.key &
+            showcase_pid=$!
+
+            cleanup() {
+              echo "kill showcase server"
+            	kill $showcase_pid
+            	# Wait for the process to die, but don't report error from the kill.
+            	wait $showcase_pid || exit $exit_code
+            }
+            trap cleanup EXIT
+
+            cd ..
+            nox -s showcase_mtls
   showcase-alternative-templates:
     docker:
       - image: python:3.8-slim
-      - image: gcr.io/gapic-images/gapic-showcase:0.6.1
+      - image: gcr.io/gapic-images/gapic-showcase:0.8.1
     steps:
       - checkout
       - run:
@@ -254,6 +317,47 @@ jobs:
       - run:
           name: Run showcase tests.
           command: nox -s showcase_alternative_templates
+  showcase-mtls-alternative-templates:
+    working_directory: /tmp/workspace
+    docker:
+      - image: python:3.8-slim
+    steps:
+      - checkout
+      - run:
+          name: Install system dependencies.
+          command: |
+            apt-get update
+            apt-get install -y curl pandoc unzip
+      - run:
+          name: Install nox.
+          command: pip install nox
+      - run:
+          name: Install protoc 3.7.1.
+          command: |
+            mkdir -p /usr/src/protoc/
+            curl --location https://github.com/google/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-x86_64.zip --output /usr/src/protoc/protoc-3.7.1.zip
+            cd /usr/src/protoc/
+            unzip protoc-3.7.1.zip
+            ln -s /usr/src/protoc/bin/protoc /usr/local/bin/protoc
+      - run:
+          name: Run showcase tests.
+          command:  |
+            mkdir gapic_showcase
+            cd gapic_showcase
+            curl -sSL https://github.com/googleapis/gapic-showcase/releases/download/v0.8.1/gapic-showcase-0.8.1-linux-amd64.tar.gz | tar xz
+            ./gapic-showcase run --mtls-ca-cert=/tmp/workspace/tests/cert/mtls.crt --mtls-cert=/tmp/workspace/tests/cert/mtls.crt --mtls-key=/tmp/workspace/tests/cert/mtls.key &
+            showcase_pid=$!
+
+            cleanup() {
+              echo "kill showcase server"
+            	kill $showcase_pid
+            	# Wait for the process to die, but don't report error from the kill.
+            	wait $showcase_pid || exit $exit_code
+            }
+            trap cleanup EXIT
+
+            cd ..
+            nox -s showcase_mtls_alternative_templates
   showcase-unit-3.6:
     docker:
       - image: python:3.6-slim
